server:
  port: 8080
  servlet:
    context-path: /TEMPLATE
spring:
  jpa:
    database: postgresql
  application:
    name: AppApplication 
  datasource:
    url: jdbc:postgresql://localhost:5432/template?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: sistemas
    password: sistemas
    driver-class-name: org.postgresql.Driver
    dbcp2:
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
